### ISSUE TITLE
(Question) Why you need to manually insert the Albedo library?

### ISSUE THREAD

**Issue by hardBSDk** [DavidPeicho/loupiote#21]
Why not configured by default?

**Comment by DavidPeicho** [comment]
Hi!

I have to move to a git version you are right. The library is heavily WIP right now, and I work on it a couple of hours per month. As long as I haven't decided on a clear architecture, I don't want to overly publish it.

You are absolutely right tho, I need to list the albedo dependency using its git repo for now.
